In [1]:
import pandas as pd
# from sklearn.preprocessing import LabelEncoder

In [34]:
songs = pd.read_csv("../Dataset/songs.csv")
print(songs.head(2))
# songs_df = pd.DataFrame(songs)

   songId        name                                 singer  userId  rating
0      27   Dil Chori  Ishers, Simar Kaur, Yo Yo Honey Singh       1     1.0
1      43  Sweetheart                               Dev Negi       1     1.0

In [35]:
user_ratings = songs.pivot_table(index=["userId"], columns= "name", values = "rating")
user_ratings

name,Aankh Marey,Aao Kabhi Haveli Pe,Apna Time Aayega,Badri Ki Dulhania,Bhare Bazaar,Bom Diggy Diggy,Chamma Chamma,Cheez Badi,Chhote Chhote Peg,Coca Cola,...,Phir Mulaaqat,Proper Patola,Qaafirana,Swag Se Swagat,Sweetheart,Tareefan,Tere Bin,Tere Naal Nachna,Tu Hi Re,Zingaat
userId,,,,,,,,,,,,,,,,,,,,,
1,9.1,10.0,1.0,NaN,NaN,6.0,NaN,NaN,8.5,NaN,...,7.0,NaN,NaN,NaN,1.0,9.5,1.0,8.6,1.0,6.0
2,NaN,6.5,9.6,6.0,NaN,6.6,NaN,5.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.5,6.4,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,5.7,5.5,NaN,NaN,NaN,NaN,...,NaN,6.5,NaN,NaN,6.9,NaN,NaN,5.8,NaN,NaN
4,7.0,6.4,NaN,6.0,6.9,6.2,6.4,NaN,NaN,6.3,...,5.1,NaN,5.4,5.1,NaN,NaN,5.3,5.6,6.1,6.5
5,6.8,5.5,NaN,6.0,NaN,NaN,NaN,NaN,5.7,NaN,...,6.1,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN

In [36]:
item_similarity_df = user_ratings.corr(method="pearson")
item_similarity_df.head()

name,Aankh Marey,Aao Kabhi Haveli Pe,Apna Time Aayega,Badri Ki Dulhania,Bhare Bazaar,Bom Diggy Diggy,Chamma Chamma,Cheez Badi,Chhote Chhote Peg,Coca Cola,...,Phir Mulaaqat,Proper Patola,Qaafirana,Swag Se Swagat,Sweetheart,Tareefan,Tere Bin,Tere Naal Nachna,Tu Hi Re,Zingaat
name,,,,,,,,,,,,,,,,,,,,,
Aankh Marey,1.000000,0.993784,NaN,NaN,NaN,-1.000000,NaN,NaN,1.0,NaN,...,0.806526,NaN,NaN,NaN,NaN,NaN,-1.000000,0.845286,-1.0,-1.0
Aao Kabhi Haveli Pe,0.993784,1.000000,-1.0,NaN,NaN,-0.739739,NaN,NaN,1.0,NaN,...,0.735697,NaN,NaN,NaN,NaN,1.0,-0.976259,0.780549,-1.0,-1.0
Apna Time Aayega,NaN,-1.000000,1.0,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-1.0,1.000000,NaN,NaN,NaN
Badri Ki Dulhania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bhare Bazaar,NaN,NaN,NaN,NaN,1.0,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN

In [37]:
def get_similar_movie(song_name, user_rating):
    similar_score= item_similarity_df[song_name]*(user_rating-5)
    similar_score = similar_score.sort_values(ascending=False)

    return similar_score

In [38]:
user = {(songs["name"][i], songs["rating"][i]) for i in songs.index if songs["userId"][i] == 1}
user

{('Aankh Marey', 9.1),
 ('Aao Kabhi Haveli Pe', 10.0),
 ('Apna Time Aayega', 1.0),
 ('Bom Diggy Diggy', 6.0),
 ('Chhote Chhote Peg', 8.5),
 ('Dil Chori', 1.0),
 ('Dil Diyan Gallan', 6.7),
 ('Galti Se Mistake', 6.0),
 ('Heeriye', 1.0),
 ('Kamariya', 6.4),
 ('Milegi Milegi', 6.2),
 ('Morni Banke', 8.7),
 ('Phir Mulaaqat', 7.0),
 ('Sweetheart', 1.0),
 ('Tareefan', 9.5),
 ('Tere Bin', 1.0),
 ('Tere Naal Nachna', 8.6),
 ('Tu Hi Re', 1.0),
 ('Zingaat', 6.0)}

In [39]:
# action_lover={
#     ("Qaafirana",10),
#     ("Galti Se Mistake",10),
#     ("Aankh Marey",1),
#     ("Gali Gali",1),
#     ("Tere Bin",10)
# }

action_lover={
    ("Tareefan",10),
    ("Aao Kabhi Haveli Pe",10),
    ("Dil Chori",10),
    ("Sweetheart",10)
}



similar_songs = []

for song,rating in user:
    similar_songs.append(get_similar_movie(song,rating))

# print(similar_movies)
similar_songs_df = pd.DataFrame(similar_songs)
# print(similar_movies_df)
print(similar_songs_df.sum().sort_values(ascending=False))

name
Tere Naal Nachna                   4.111268e+01
Aao Kabhi Haveli Pe                4.104941e+01
Aankh Marey                        3.532077e+01
Phir Mulaaqat                      3.498956e+01
Morni Banke                        3.460000e+01
Chhote Chhote Peg                  2.120000e+01
Kamariya                           1.870709e+01
Milegi Milegi                      1.802800e+01
Tareefan                           1.500000e+01
Issaqbaazi                         5.241963e+00
Husn Parcham                       5.000000e+00
Bhare Bazaar                       1.800000e+00
Dhadak Title Track                 1.800000e+00
Dekhte Dekhte                      1.800000e+00
Daaru Wargi                        1.800000e+00
Khalibali                          4.000000e-01
Ek Ladki Ko Dekha Toh Aisa Laga    4.000000e-01
Doori                              1.265654e-14
Coca Cola                          0.000000e+00
Proper Patola                      0.000000e+00
Paniyon Sa                         0.000000e+00
Swag Se Swagat                     0.000000e+00
Mile Ho Tum (Reprise)              0.000000e+00
Dholida                            0.000000e+00
Kala Chashma                       0.000000e+00
Badri Ki Dulhania                  0.000000e+00
Chamma Chamma                      0.000000e+00
Gud Naal Ishq Mitha                0.000000e+00
Cheez Badi                         0.000000e+00
Dilbar                             0.000000e+00
Dil Meri Na Sune                   0.000000e+00
Qaafirana                          0.000000e+00
Gali Gali                         -4.000000e-01
Mere Gully Mein                   -1.507382e+00
Mungda                            -1.800000e+00
Galti Se Mistake                  -2.949061e+00
Namo Namo                         -4.600000e+00
Sweetheart                        -1.300000e+01
Apna Time Aayega                  -1.500000e+01
Dil Diyan Gallan                  -1.500000e+01
Bom Diggy Diggy                   -2.460778e+01
Tu Hi Re                          -3.460000e+01
Zingaat                           -3.460000e+01
Heeriye                           -3.592430e+01
Dil Chori                         -3.947927e+01
Tere Bin                          -4.082773e+01
dtype: float64

In [4]:
# label_encoder = LabelEncoder()
# songs['singer_encoded'] = label_encoder.fit_transform(songs['singer'])

# # Create a combined feature of singer and rating
# songs['singer_rating'] = songs.apply(lambda row: f"{row['singer_encoded']} ({row['rating']})", axis=1)
# songs.head()


# # for i in range(len(songs)):
# #     songs.at[i, 'singer_rating'] = f"{songs.at[i, 'singer']} ({songs.at[i, 'rating']})"


# # # print(songs.head())
# user_data = songs.pivot_table(index=["userId"], columns="songId", values="singer_rating")
# user_data.head()

In [5]:
# import pandas as pd
# import random

# # Sample songs data
# songs = [
#     (1, "Aankh Marey", "Kumar Sanu, Mika Singh, Neha Kakkar"),
#     (2, "Coca Cola", "Neha Kakkar, Tony Kakkar"),
#     (3, "Apna Time Aayega", "Ranveer Singh"),
#     (4, "Mungda", "Jyotica Tangri, Shaan, Subhro Ganguly"),
#     (5, "Tere Bin", "Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi"),
#     (6, "Gali Gali", "Neha Kakkar"),
#     (7, "Chamma Chamma", "Arun, Ikka, Neha Kakkar, Romy"),
#     (8, "Mere Gully Mein", "Ranveer Singh"),
#     (9, "Kamariya", "Darshan Raval"),
#     (10, "Ek Ladki Ko Dekha Toh Aisa Laga", "Darshan Raval, Rochak Kohli"),
#     (11, "Swag Se Swagat", "Neha Bhasin, Vishal Dadlani"),
#     (12, "Poster Lagwa Do", "Mika Singh, Sunanda Sharma"),
#     (13, "Daaru Wargi", "Guru Randhawa"),
#     (14, "Dilbar", "Dhvani Bhanushali, Ikka, Neha Kakkar"),
#     (15, "Proper Patola", "Aastha Gill, Badshah, Diljit Dosanjh"),
#     (16, "Doori", "Ranveer Singh"),
#     (17, "Dil Diyan Gallan", "Atif Aslam"),
#     (18, "Husn Parcham", "Bhoomi Trivedi, Raja Kumari"),
#     (19, "Bom Diggy Diggy", "Jasmin Walia, Zack Knight"),
#     (20, "Issaqbaazi", "Divya Kumar, Sukhwinder Singh"),
#     (21, "Mere Naam Tu", "Abhay Jodhpurkar"),
#     (22, "High Rated Gabru Nawabzaade", "Guru Randhawa"),
#     (23, "Dekhte Dekhte", "Atif Aslam"),
#     (24, "Zingaat", "Ajay, Atul"),
#     (25, "Tareefan", "Badshah"),
#     (26, "Mile Ho Tum (Reprise)", "Neha Kakkar, Tony Kakkar"),
#     (27, "Dil Chori", "Ishers, Simar Kaur, Yo Yo Honey Singh"),
#     (28, "Tere Naal Nachna", "Badshah, Sunanda Sharma"),
#     (29, "Dil Meri Na Sune", "Atif Aslam"),
#     (30, "Dhadak Title Track", "Ajay Gogavale, Shreya Ghoshal"),
#     (31, "Heeriye", "Deep Money, Meet Bros, Neha Bhasin"),
#     (32, "Chogada", "Asees Kaur, Darshan Raval"),
#     (33, "Gud Naal Ishq Mitha", "Harshdeep Kaur, Navraj Hans"),
#     (34, "Paniyon Sa", "Atif Aslam, Tulsi Kumar"),
#     (35, "Milegi Milegi", "Mika Singh"),
#     (36, "Morni Banke", "Guru Randhawa, Neha Kakkar"),
#     (37, "Bhare Bazaar", "B Praak, Badshah, Payal Dev, Vishal Dadlani"),
#     (38, "Khalibali", "Shivam Pathak"),
#     (39, "Aao Kabhi Haveli Pe", "Badshah, Jigar, Nikhita Gandhi, Sachin Sanghvi"),
#     (40, "Badri Ki Dulhania", "Dev Negi, Ikka, Monali Thakur, Neha Kakkar"),
#     (41, "Cheez Badi", "Neha Kakkar, Udit Narayan"),
#     (42, "Dholida", "Neha Kakkar, Palak Muchchal, Raja Hassan, Udit Narayan"),
#     (43, "Sweetheart", "Dev Negi"),
#     (44, "Namo Namo", "Amit Trivedi"),
#     (45, "Qaafirana", "Arijit Singh, Nikhita Gandhi"),
#     (46, "Tu Hi Re", "Armaan Malik, Shashaa Tirupati"),
#     (47, "Chhote Chhote Peg", "Navraj Hans, Neha Kakkar, Yo Yo Honey Singh"),
#     (48, "Galti Se Mistake", "Amit Mishra, Arijit Singh"),
#     (49, "Phir Mulaaqat", "Jubin Nautiyal"),
#     (50, "Kala Chashma", "Amar Arshi, Badshah, Neha Kakkar"),
# ]

# # User preferences
# user_preferences = {
#     1: ["Neha Kakkar", "Badshah"],  # User 1 likes Neha Kakkar and Badshah
#     2: ["Ranveer Singh", "Atif Aslam"],  # User 2 likes Ranveer Singh and Atif Aslam
#     3: ["Guru Randhawa", "Tony Kakkar"],  # User 3 likes Guru Randhawa and Tony Kakkar
#     4: ["Amit Trivedi", "Shreya Ghoshal"],  # User 4 likes Amit Trivedi and Shreya Ghoshal
#     5: ["Arijit Singh", "Dhvani Bhanushali"]  # User 5 likes Arijit Singh and Dhvani Bhanushali
# }

# # Generate ratings
# ratings = []
# for user_id in range(1, 6):
#     preferred_singers = user_preferences[user_id]
#     for song in songs:
#         song_id, name, singer = song
#         if any(singer_name in singer for singer_name in preferred_singers):
#             rating = round(random.uniform(8.5, 10), 1)  # Higher rating for preferred singers
#         else:
#             rating = round(random.uniform(5.0, 7.0), 1)  # Lower rating for others
#         ratings.append((song_id, name, singer, user_id, rating))

# # Create DataFrame
# df = pd.DataFrame(ratings, columns=["songId", "name", "singer", "userId", "rating"])

# # Shuffle and sample 100 ratings
# df = df.sample(100).reset_index(drop=True)

# # Save DataFrame to CSV
# df.to_csv("user_song_ratings.csv", index=False)

# # Display DataFrame
# print(df.head())

   songId                 name  \
0      40    Badri Ki Dulhania
1      27            Dil Chori
2      28     Tere Naal Nachna
3      39  Aao Kabhi Haveli Pe
4      16                Doori

                                           singer  userId  rating
0      Dev Negi, Ikka, Monali Thakur, Neha Kakkar       4     6.0
1           Ishers, Simar Kaur, Yo Yo Honey Singh       3     6.2
2                         Badshah, Sunanda Sharma       1     8.6
3  Badshah, Jigar, Nikhita Gandhi, Sachin Sanghvi       5     5.5
4                                   Ranveer Singh       2     9.9